# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/phishingdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rishitha@89

# Auto-create tables (magic!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8080